services:
  cassandra:
    image: 'cassandra:latest'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042:9042'
    volumes:
      - './ssl:/opt/cassandra/conf/ssl'
      - './ssl/cassandra.yaml:/opt/cassandra/conf/cassandra.yaml'
