services:
  redis:
    image: 'redis:latest'
    ports:
      - '6380:6380'
    expose:
      - 6380
    volumes:
      - ./redis-ssl:/tls:ro
      - ./redis-ssl/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
